import {
  Star, Zap, Shield, Target, Wifi, Cpu, Server, Database,
  Lock, Unlock, Eye, Fingerprint, Activity, Box, Truck,
  Factory, Cog, Gauge, Thermometer, Signal, Battery,
  Cloud, HardDrive, Laptop, Smartphone, Camera, Video, Volume2,
  Mail, MessageSquare, PhoneCall, MapPin, User, Users, Award, Medal,
  TrendingUp, BarChart2, RefreshCw, CheckCircle, AlertCircle, Info,
  HelpCircle, Lightbulb, Rocket, Globe, Compass, Car, Home, Building,
  ShoppingCart, Tag, Heart, ThumbsUp, Share2, Gift, File, FileText,
  Grid, Layout, Maximize2, ZoomIn, Edit2, Settings,
} from 'lucide-react';

export const DOC_TYPES = ['使用说明书', '安装手册', '驱动程序', 'CAD图纸', '产品规格书', '维护手册', '其他'];
export const FILE_FORMATS = ['PDF', 'ZIP', 'DXF', 'EXE', 'DOC', 'STEP', 'IGES'];

export const ICON_LIST = [
  { name: 'Star', icon: Star },
  { name: 'Zap', icon: Zap },
  { name: 'Shield', icon: Shield },
  { name: 'Target', icon: Target },
  { name: 'Wifi', icon: Wifi },
  { name: 'Cpu', icon: Cpu },
  { name: 'Server', icon: Server },
  { name: 'Database', icon: Database },
  { name: 'Lock', icon: Lock },
  { name: 'Unlock', icon: Unlock },
  { name: 'Eye', icon: Eye },
  { name: 'Fingerprint', icon: Fingerprint },
  { name: 'Activity', icon: Activity },
  { name: 'Box', icon: Box },
  { name: 'Truck', icon: Truck },
  { name: 'Factory', icon: Factory },
  { name: 'Cog', icon: Cog },
  { name: 'Gauge', icon: Gauge },
  { name: 'Thermometer', icon: Thermometer },
  { name: 'Signal', icon: Signal },
  { name: 'Battery', icon: Battery },
  { name: 'Cloud', icon: Cloud },
  { name: 'HardDrive', icon: HardDrive },
  { name: 'Laptop', icon: Laptop },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Camera', icon: Camera },
  { name: 'Video', icon: Video },
  { name: 'Volume2', icon: Volume2 },
  { name: 'Mail', icon: Mail },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'PhoneCall', icon: PhoneCall },
  { name: 'MapPin', icon: MapPin },
  { name: 'User', icon: User },
  { name: 'Users', icon: Users },
  { name: 'Award', icon: Award },
  { name: 'Medal', icon: Medal },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'BarChart', icon: BarChart2 },
  { name: 'RefreshCw', icon: RefreshCw },
  { name: 'CheckCircle', icon: CheckCircle },
  { name: 'AlertCircle', icon: AlertCircle },
  { name: 'Info', icon: Info },
  { name: 'HelpCircle', icon: HelpCircle },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Rocket', icon: Rocket },
  { name: 'Globe', icon: Globe },
  { name: 'Compass', icon: Compass },
  { name: 'Car', icon: Car },
  { name: 'Home', icon: Home },
  { name: 'Building', icon: Building },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Tag', icon: Tag },
  { name: 'Heart', icon: Heart },
  { name: 'ThumbsUp', icon: ThumbsUp },
  { name: 'Share2', icon: Share2 },
  { name: 'Gift', icon: Gift },
  { name: 'File', icon: File },
  { name: 'FileText', icon: FileText },
  { name: 'Grid', icon: Grid },
  { name: 'Layout', icon: Layout },
  { name: 'Maximize', icon: Maximize2 },
  { name: 'ZoomIn', icon: ZoomIn },
  { name: 'Edit', icon: Edit2 },
  { name: 'Settings', icon: Settings },
];
